name: Terraform CI/CD Workflows

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
        description: 'Name of the repository calling the workflow'
      deploy_env:
        required: true
        type: string
        description: 'Deployment environment (e.g., staging, production)'
      terraform_version:
        required: true
        type: string
        description: 'Version of Terraform to use'
      plan_and_apply:
        required: true
        type: boolean
        description: 'Whether to plan and apply changes'

jobs:
  terraform:
    name: Terraform CI/CD
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo_name }}

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ inputs.terraform_version }}

      # Step 3: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Step 5: Terraform Format
      - name: Terraform Format
        run: terraform fmt -check

      # Step 6: Install and Run TFLint
      - name: Install and Run TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --version
          tflint

      # Step 7: Advanced SonarQube Scanner (Manual Integration)
      - name: SonarQube Scanner
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
          unzip sonar-scanner.zip -d $HOME
          export PATH="$HOME/sonar-scanner-4.8.0.2856-linux/bin:$PATH"
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.PROJECT_KEY }} \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.exclusions="*/tests/*" \
            -Dsonar.qualitygate.wait=true || true

      # Step 8: Terraform Plan
      - name: Terraform Plan
        if: ${{ inputs.plan_and_apply == 'true' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1 # Update with your region
        run: terraform plan

      # Step 9: Terraform Apply
      - name: Terraform Apply
        if: ${{ inputs.plan_and_apply == 'true' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1 # Update with your region
        run: terraform apply -auto-approve
